### ISSUE TITLE
Doc issue: do I have to init or not?

### ISSUE THREAD

**Issue by infews** [iros/deck.js-codemirror#13]
Between your readme and your code, I'm a little confused. Do I need to set codemirror options inorder to use this extension? Or does Codemirror "just work" when it's included as you show in the README?

For example, do I need to specify the theme, or does the Codemirror CSS do the right thing?

**Comment by iros** [comment]
Sorry about the confusion. I highly recommend going through my sample slides which are linked to on the README as they demonstrate exactly what you need to do.
You do not need to instantiate codemirror itself, all the options are passed individually on code blocks as attributes. As long as you set the right attributes, codemirror will just work.

You need to specify a theme based on the one you include css for.
Does this help? Do tell me if some particular part of my documentation is lacking because the assumption was that it contains complete instructions for getting things up and running.

Thanks,
-- Irene
